# Generated by Django 3.1.4 on 2021-03-05 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registerStudent', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registerstudent',
            old_name='img',
            new_name='studenImage',
        ),
    ]
