# Generated by Django 3.1.4 on 2021-03-05 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registerStudent', '0003_auto_20210305_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerstudent',
            name='studentImage',
            field=models.ImageField(blank=True, null=True, upload_to='students/'),
        ),
    ]
